/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:36 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WebCore/DOMHTMLElement.h>

@class DOMHTMLFormElement, NSString;

@interface DOMHTMLTextAreaElement : DOMHTMLElement

@property (assign) BOOL autofocus; 
@property (assign) int cols; 
@property (assign) BOOL disabled; 
@property (readonly) DOMHTMLFormElement * form; 
@property (copy) NSString * name; 
@property (assign) BOOL readOnly; 
@property (assign) int rows; 
@property (copy,readonly) NSString * type; 
@property (copy) NSString * defaultValue; 
@property (copy) NSString * value; 
@property (readonly) BOOL willValidate; 
@property (assign) int selectionStart; 
@property (assign) int selectionEnd; 
@property (copy) NSString * accessKey; 
-(int)structuralComplexityContribution;
-(int)_autocapitalizeType;
-(BOOL)_isEdited;
-(void)setReadOnly:(BOOL)arg1 ;
-(NSString *)accessKey;
-(void)setAccessKey:(NSString *)arg1 ;
-(BOOL)autofocus;
-(void)setAutofocus:(BOOL)arg1 ;
-(BOOL)willValidate;
-(id)validationMessage;
-(BOOL)checkValidity;
-(void)setCustomValidity:(id)arg1 ;
-(id)autocomplete;
-(void)setAutocomplete:(id)arg1 ;
-(void)setAutocorrect:(BOOL)arg1 ;
-(id)autocapitalize;
-(void)setAutocapitalize:(id)arg1 ;
-(int)cols;
-(void)setCols:(int)arg1 ;
-(id)dirName;
-(void)setDirName:(id)arg1 ;
-(BOOL)required;
-(int)selectionStart;
-(void)setSelectionStart:(int)arg1 ;
-(int)selectionEnd;
-(void)setSelectionEnd:(int)arg1 ;
-(id)selectionDirection;
-(void)setSelectionDirection:(id)arg1 ;
-(void)select;
-(void)setRangeText:(id)arg1 ;
-(void)setRangeText:(id)arg1 start:(unsigned)arg2 end:(unsigned)arg3 selectionMode:(id)arg4 ;
-(void)setSelectionRange:(int)arg1 end:(int)arg2 ;
-(unsigned)textLength;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(NSString *)type;
-(NSString *)value;
-(void)setValue:(NSString *)arg1 ;
-(void)setPlaceholder:(id)arg1 ;
-(void)setMaxLength:(int)arg1 ;
-(BOOL)disabled;
-(void)setDisabled:(BOOL)arg1 ;
-(DOMHTMLFormElement *)form;
-(BOOL)autocorrect;
-(id)placeholder;
-(int)rows;
-(BOOL)readOnly;
-(NSString *)defaultValue;
-(void)setDefaultValue:(NSString *)arg1 ;
-(void)setRows:(int)arg1 ;
-(id)labels;
-(int)maxLength;
-(void)setRequired:(BOOL)arg1 ;
-(id)validity;
-(void)setWrap:(id)arg1 ;
-(id)wrap;
@end

