/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:36 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <WebCore/WebCore-Structs.h>
@interface WebCoreTextTrackRepresentationIOSHelper : NSObject {

	TextTrackRepresentationIOS* _parent;

}

@property (assign) TextTrackRepresentationIOS* parent; 
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(id)actionForLayer:(id)arg1 forKey:(id)arg2 ;
-(id)initWithParent:(TextTrackRepresentationIOS*)arg1 ;
-(TextTrackRepresentationIOS*)parent;
-(void)setParent:(TextTrackRepresentationIOS*)arg1 ;
@end

