/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:56 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/AssistantUI.framework/AssistantUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol AFSpeechDelegate <NSObject>
@optional
-(void)assistantConnectionSpeechRecordingWillBegin:(id)arg1;
-(void)assistantConnection:(id)arg1 speechRecordingDidBeginOnAVRecordRoute:(id)arg2;
-(void)assistantConnection:(id)arg1 speechRecordingDidChangeAVRecordRoute:(id)arg2;
-(void)assistantConnectionSpeechRecordingDidDetectStartpoint:(id)arg1;
-(void)assistantConnectionSpeechRecordingDidEnd:(id)arg1;
-(void)assistantConnectionSpeechRecordingDidCancel:(id)arg1;
-(void)assistantConnection:(id)arg1 speechRecordingDidFail:(id)arg2;
-(void)assistantConnectionDidChangeAudioRecordingPower:(id)arg1;
-(void)assistantConnection:(id)arg1 speechRecognitionDidFail:(id)arg2;
-(void)assistantConnection:(id)arg1 speechRecognized:(id)arg2;
-(void)assistantConnection:(id)arg1 speechRecognizedPartialResult:(id)arg2;

@end

