/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:56 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/AssistantUI.framework/AssistantUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SiriUISiriStatusViewDelegate <NSObject>
@required
-(float)audioLevelForSiriStatusView:(id)arg1;
-(void)siriStatusViewWasTapped:(id)arg1;
-(void)siriStatusViewHoldDidBegin:(id)arg1;
-(void)siriStatusViewHoldDidEnd:(id)arg1;

@end

