/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:36 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/Symptoms.framework/Frameworks/SymptomAnalytics.framework/SymptomAnalytics
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSDate, NSNumber;

@interface DemoLiveUsage : NSManagedObject

@property (nonatomic,retain) NSDate * timeStamp; 
@property (nonatomic,retain) NSNumber * wifiIN; 
@property (nonatomic,retain) NSNumber * wifiOUT; 
@property (nonatomic,retain) NSNumber * wwanIN; 
@property (nonatomic,retain) NSNumber * wwanOUT; 
@property (nonatomic,retain) NSNumber * incarnation; 
@end

