/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:53 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/Message.framework/Message
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface MFAttachmentBundle : NSObject
+(BOOL)isFileBundleURL:(id)arg1 ;
+(id)dataForFileBundleURL:(id)arg1 ;
+(id)_stripBundlePath:(id)arg1 entryPath:(id)arg2 ;
@end

