/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:18 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IKAppDataStoring
@required
-(unsigned long long)count;
-(void)clear;
-(id)keyAtIndex:(unsigned long long)arg1;
-(id)getDataForKey:(id)arg1;
-(unsigned long long)setData:(id)arg1 forKey:(id)arg2;
-(void)removeDataForKey:(id)arg1;

@end

