/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:18 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface IKCSSMediaQueryExpression : NSObject {

	long long _type;
	NSString* _key;
	NSString* _stringValue;
	NSString* _dimension;
	NSString* _mediaType;
	double _doubleValue;

}

@property (assign) long long type;                                //@synthesize type=_type - In the implementation block
@property (nonatomic,retain) NSString * key;                      //@synthesize key=_key - In the implementation block
@property (nonatomic,retain) NSString * stringValue;              //@synthesize stringValue=_stringValue - In the implementation block
@property (nonatomic,retain) NSString * dimension;                //@synthesize dimension=_dimension - In the implementation block
@property (nonatomic,retain) NSString * mediaType;                //@synthesize mediaType=_mediaType - In the implementation block
@property (assign) double doubleValue;                            //@synthesize doubleValue=_doubleValue - In the implementation block
-(id)description;
-(double)doubleValue;
-(NSString *)key;
-(void)setType:(long long)arg1 ;
-(long long)type;
-(NSString *)stringValue;
-(void)setStringValue:(NSString *)arg1 ;
-(void)setKey:(NSString *)arg1 ;
-(NSString *)dimension;
-(void)setDimension:(NSString *)arg1 ;
-(id)valueAsString;
-(NSString *)mediaType;
-(void)setMediaType:(NSString *)arg1 ;
-(BOOL)evaluate;
-(void)setDoubleValue:(double)arg1 ;
@end

