/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:19 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ITMLKit/IKCSSParseObject.h>

@class NSArray, IKCSSParseBlock;

@interface IKCSSParseRule : IKCSSParseObject {

	NSArray* _prelude;
	IKCSSParseBlock* _block;

}

@property (nonatomic,retain) NSArray * prelude;                    //@synthesize prelude=_prelude - In the implementation block
@property (nonatomic,retain) IKCSSParseBlock * block;              //@synthesize block=_block - In the implementation block
-(id)init;
-(id)description;
-(IKCSSParseBlock *)block;
-(void)setBlock:(IKCSSParseBlock *)arg1 ;
-(NSArray *)prelude;
-(void)setPrelude:(NSArray *)arg1 ;
@end

