/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:19 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ITMLKit/IKJSObject.h>
#import <libobjc.A.dylib/IKJSDOMImplementation.h>
#import <libobjc.A.dylib/IKJSDOMImplementationLS.h>

@interface IKDOMImplementation : IKJSObject <IKJSDOMImplementation, IKJSDOMImplementationLS>
-(id)createDocument:(id)arg1 :(id)arg2 ;
-(id)createLSSerializer;
-(id)createLSInput;
-(id)createLSParser:(long long)arg1 :(id)arg2 ;
@end

