/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:19 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ITMLKit/IKJSObject.h>
#import <libobjc.A.dylib/IKJSPlaylist.h>

@protocol IKJSPlaylist <JSExport>
@property (nonatomic,readonly) unsigned long long length; 
@property (assign,nonatomic) long long endAction; 
@required
-(id)init;
-(unsigned long long)length;
-(id)pop;
-(id)item:(long long)arg1;
-(void)push:(id)arg1;
-(void)setEndAction:(long long)arg1;
-(long long)endAction;
-(id)splice:(long long)arg1 :(long long)arg2 :(id)arg3;

@end


@class IKAppPlaylistBridge;

@interface IKJSPlaylist : IKJSObject <IKJSPlaylist> {

	IKAppPlaylistBridge* _bridge;

}

@property (nonatomic,readonly) IKAppPlaylistBridge * bridge;              //@synthesize bridge=_bridge - In the implementation block
@property (nonatomic,readonly) unsigned long long length; 
@property (assign,nonatomic) long long endAction; 
-(id)init;
-(unsigned long long)length;
-(id)pop;
-(id)item:(long long)arg1 ;
-(void)push:(id)arg1 ;
-(void)setEndAction:(long long)arg1 ;
-(long long)endAction;
-(id)splice:(long long)arg1 :(long long)arg2 :(id)arg3 ;
-(IKAppPlaylistBridge *)bridge;
@end

