/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:23 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SKUIItemStateCenterObserver <NSObject>
@optional
-(void)itemStateCenter:(id)arg1 itemStatesChanged:(id)arg2;
-(void)itemStateCenter:(id)arg1 didFinishPurchases:(id)arg2;
-(void)itemStateCenterMediaLibrariesDidChange:(id)arg1;
-(void)itemStateCenterRestrictionsChanged:(id)arg1;

@end

