/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:27 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SKUIProductPageHeaderViewDelegate <NSObject>
@optional
-(void)productPageHeaderView:(id)arg1 didSelectURL:(id)arg2;
-(id)metricsControllerForProductPageHeader:(id)arg1;
-(void)productPageHeaderView:(id)arg1 didSelectSectionIndex:(long long)arg2;
-(void)productPageHeaderView:(id)arg1 didReloadItemOffer:(id)arg2;
-(void)productPageHeaderViewDidWantAskPermissionBanner:(id)arg1;

@end

