/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:28 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <StoreKitUI/StoreKitUI-Structs.h>
#import <UIKit/UITableViewCell.h>

@class UIView;

@interface SKUICategoryTableViewCell : UITableViewCell {

	UIView* _separatorView;
	CGSize _expectedImageSize;
	BOOL _layoutNeedsLayout;

}

@property (assign,nonatomic) CGSize expectedImageSize;              //@synthesize expectedImageSize=_expectedImageSize - In the implementation block
-(void)setFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setBounds:(CGRect)arg1 ;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(void)setExpectedImageSize:(CGSize)arg1 ;
-(CGSize)expectedImageSize;
@end

