/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:27 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UIView;

@interface SKUIOverlayFlipTransition : NSObject {

	UIView* _flipSourceView;

}

@property (nonatomic,retain) UIView * flipSourceView;              //@synthesize flipSourceView=_flipSourceView - In the implementation block
-(void)setFlipSourceView:(UIView *)arg1 ;
-(UIView *)flipSourceView;
@end

