/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:29 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <StoreKitUI/SKUIViewElement.h>

@class NSString;

@interface SKUICharityTemplateViewElement : SKUIViewElement {

	NSString* _campaignIdentifier;
	NSString* _charityMetadataURLString;

}

@property (nonatomic,readonly) NSString * campaignIdentifier;                    //@synthesize campaignIdentifier=_campaignIdentifier - In the implementation block
@property (nonatomic,readonly) NSString * charityMetadataURLString;              //@synthesize charityMetadataURLString=_charityMetadataURLString - In the implementation block
-(id)initWithDOMElement:(id)arg1 parent:(id)arg2 elementFactory:(id)arg3 ;
-(id)applyUpdatesWithElement:(id)arg1 ;
-(NSString *)campaignIdentifier;
-(NSString *)charityMetadataURLString;
@end

