/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:23 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SKUIOnboardingAffiliationCirclesDelegate <NSObject>
@optional
-(void)onboardingCirclesDidChangeAffiliationItems:(id)arg1;
-(void)onboardingCircles:(id)arg1 didRemoveAffiliationItem:(id)arg2;
-(void)onboardingCircles:(id)arg1 didSelectAffiliationItem:(id)arg2 atIndex:(long long)arg3;

@end

