/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:52 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/FMF.framework/FMF
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FMLoggerDelegate <NSObject>
@required
-(void)logAtLevel:(unsigned)arg1 facility:(id)arg2 path:(const char*)arg3 lineNumber:(long long)arg4 function:(const char*)arg5 message:(id)arg6;

@end

