/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:51 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/SpringBoardFoundation.framework/SpringBoardFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ISPlayerViewDelegate <NSObject>
@optional
-(id)irisPlayerView:(id)arg1 delegateForGestureRecognizer:(id)arg2;
-(id)irisPlayerViewViewHostingGestureRecognizers:(id)arg1;
-(void)playerViewGestureRecognizerDidChange:(id)arg1;
-(void)playerViewPlayerItemDidChange:(id)arg1;
-(void)playerViewPlaybackStateDidChange:(id)arg1;
-(void)playerViewIsInteractingDidChange:(id)arg1;
-(void)playerViewWillBeginVisualPlayback:(id)arg1;
-(void)playerViewDidEndVisualPlayback:(id)arg1;
-(void)playerViewWillPlaybackVideoAssetToEnd:(id)arg1;
-(void)playerViewDidPlaybackVideoAssetToEnd:(id)arg1;

@end

