/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:45 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/MDM.framework/MDM
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MDM/MDM-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface MCSoftwareUpdateInstallOptions : NSObject <NSCopying> {

	BOOL _overridePhoneCall;

}

@property (assign,nonatomic) BOOL overridePhoneCall;              //@synthesize overridePhoneCall=_overridePhoneCall - In the implementation block
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)overridePhoneCall;
-(void)setOverridePhoneCall:(BOOL)arg1 ;
@end

