/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:29 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/PersistentConnection.framework/PersistentConnection
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PCLogging : NSObject
+(void)logAtLevel:(int)arg1 delegate:(id)arg2 format:(id)arg3 ;
+(void)logKeepAliveInterval:(double)arg1 forServiceIdentifier:(id)arg2 ;
+(void)logAtLevel:(int)arg1 delegate:(id)arg2 format:(id)arg3 arguments:(char*)arg4 ;
+(id)_fileNameForIdentifier:(id)arg1 ;
+(id)_facilityForIdentifier:(id)arg1 ;
+(/*^block*/id)_formatBlock;
+(void)_configureLogFacilityIfNeeded:(id)arg1 ;
+(void)_appendString:(id)arg1 toFileNamed:(id)arg2 ;
+(id)getMainBundleId;
+(void)_printLoggingConfig;
+(void)enableFileLogging:(BOOL)arg1 ;
+(void)initialize;
+(id)logFileDirectory;
+(BOOL)loggingEnabledForLevel:(int)arg1 ;
+(void)enableConsoleLoggingForLevel:(int)arg1 ;
+(void)enableLoggingForCustomHandler:(/*^block*/id)arg1 ;
@end

