/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:29 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/PersistentConnection.framework/PersistentConnection
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PCPersistentIdentifiers : NSObject
+(id)processNameAndPidIdentifier;
+(unsigned long long)hostUniqueIdentifier;
+(id)processNamePidAndStringIdentifier:(id)arg1 ;
+(int)pidFromMatchingIdentifer:(id)arg1 ;
+(id)_processNamePrefix;
@end

