/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:36 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreUI/CUINamedLookup.h>

@class NSString, NSData;

@interface CUINamedData : CUINamedLookup

@property (nonatomic,copy,readonly) NSString * utiType; 
@property (nonatomic,copy,readonly) NSData * data; 
-(id)initWithName:(id)arg1 usingRenditionKey:(id)arg2 fromTheme:(unsigned long long)arg3 ;
-(id)_renditionName;
-(id)description;
-(NSData *)data;
-(NSString *)utiType;
@end

