/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:37 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreUI/CUIThemeSchemaPSDLayer.h>

@class CUIThemeSchemaRendition;

@interface CUIThemeSchemaPSDRenditionLayer : CUIThemeSchemaPSDLayer {

	CUIThemeSchemaRendition* rendition;

}

@property (nonatomic,retain) CUIThemeSchemaRendition * rendition; 
-(CUIThemeSchemaRendition *)rendition;
-(void)setRendition:(CUIThemeSchemaRendition *)arg1 ;
-(void)dealloc;
@end

