/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:25 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/PassKit.framework/PassKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PassKit/PKPassFrontFaceView.h>

@class UIImageView;

@interface PKPassBoardingPassFrontFaceView : PKPassFrontFaceView {

	UIImageView* _transitImageView;
	UIImageView* _footerImageView;

}
-(void)dealloc;
-(void)layoutSubviews;
-(id)shortFaceTemplate;
-(void)createBodyContentViews;
-(id)_transitGlyphForTransitType:(long long)arg1 ;
-(void)setShowsBarcodeView:(BOOL)arg1 animated:(BOOL)arg2 ;
-(id)shortScrunchedFaceTemplate;
-(id)tallFaceTemplate;
@end

