/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:25 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/PassKit.framework/PassKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol PKPassPersonalizationCellDelegate <NSObject>
@required
-(BOOL)personalizationCellShouldBeginEditing:(id)arg1;
-(BOOL)personalizationCellShouldReturn:(id)arg1;
-(void)personalizationCellDidChangeValue:(id)arg1;

@end

