/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:26 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/PassKit.framework/PassKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <PassKit/PassKit-Structs.h>
@interface PKPassSnapshotCacheItem : NSObject {

	CGImageRef _image;
	double _scale;

}
-(void)dealloc;
-(id)initWithCGImage:(CGImageRef)arg1 scale:(double)arg2 ;
-(id)UIImageFromCache;
@end

