/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:13:06 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/iCloudQuotaUI.framework/iCloudQuotaUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class _ICQServiceSpecification, UIImageView, UILabel;

@interface ICQServiceView : UIView {

	_ICQServiceSpecification* _serviceSpecification;
	UIImageView* _imageView;
	UILabel* _descriptionLabel;

}

@property (nonatomic,retain) _ICQServiceSpecification * serviceSpecification;              //@synthesize serviceSpecification=_serviceSpecification - In the implementation block
@property (nonatomic,retain) UIImageView * imageView;                                      //@synthesize imageView=_imageView - In the implementation block
@property (nonatomic,retain) UILabel * descriptionLabel;                                   //@synthesize descriptionLabel=_descriptionLabel - In the implementation block
-(UIImageView *)imageView;
-(void)setImageView:(UIImageView *)arg1 ;
-(UILabel *)descriptionLabel;
-(void)setDescriptionLabel:(UILabel *)arg1 ;
-(void)setServiceSpecification:(_ICQServiceSpecification *)arg1 ;
-(_ICQServiceSpecification *)serviceSpecification;
@end

