/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:13:06 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/iCloudQuotaUI.framework/iCloudQuotaUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <iCloudQuotaUI/ICQViewController.h>

@class _ICQUpgradeCompletePageSpecification;

@interface ICQUpgradeCompleteViewController : ICQViewController {

	_ICQUpgradeCompletePageSpecification* _upgradeCompletePageSpecification;

}

@property (nonatomic,retain) _ICQUpgradeCompletePageSpecification * upgradeCompletePageSpecification;              //@synthesize upgradeCompletePageSpecification=_upgradeCompletePageSpecification - In the implementation block
+(BOOL)supportsPageClassIdentifier:(id)arg1 ;
-(void)loadView;
-(id)initWithUpgradeCompletePageSpecification:(id)arg1 ;
-(id)initWithPageSpecification:(id)arg1 ;
-(_ICQUpgradeCompletePageSpecification *)upgradeCompletePageSpecification;
-(void)setUpgradeCompletePageSpecification:(_ICQUpgradeCompletePageSpecification *)arg1 ;
@end

