/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:23 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FTUserConfiguration : NSObject

@property (assign,nonatomic) BOOL cellularFaceTimeEnabled; 
@property (assign,nonatomic) BOOL allowAnyNetwork; 
@property (nonatomic,readonly) BOOL _nonWifiFaceTimeEntitled; 
+(id)sharedInstance;
-(BOOL)_nonWifiFaceTimeEntitled;
-(BOOL)_adequateInternalOrCarrierInstall;
-(void)setAllowAnyNetwork:(BOOL)arg1 ;
-(BOOL)allowAnyNetwork;
-(BOOL)cellularFaceTimeEnabled;
-(void)setCellularFaceTimeEnabled:(BOOL)arg1 ;
@end

