/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:46 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/MusicCarDisplayUI.framework/MusicCarDisplayUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MusicCarDisplayUI/MCDSectionedTableViewController.h>

@interface MCDAudiobooksTableViewController : MCDSectionedTableViewController
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(id)viewControllerForRowAtIndexPath:(id)arg1 ;
@end

