/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:46 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/MusicCarDisplayUI.framework/MusicCarDisplayUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray;

@interface MCDBrowserIdentifiers : NSObject {

	BOOL _showSubscriptionContent;
	double _maxImageWidth;

}

@property (nonatomic,readonly) NSArray * cellIdentifiers; 
@property (nonatomic,readonly) double maxImageWidth;                   //@synthesize maxImageWidth=_maxImageWidth - In the implementation block
+(id)sharedInstance;
-(id)init;
-(id)images;
-(id)localizedStrings;
-(NSArray *)cellIdentifiers;
-(id)selectedImages;
-(double)maxImageWidth;
@end

