/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:13:01 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/VisualAlert.framework/VisualAlert
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <VisualAlert/__AXVisualAlertSBBulletinSoundController_super.h>

@interface AXVisualAlertSBBulletinSoundController : __AXVisualAlertSBBulletinSoundController_super
+(id)safeCategoryTargetClassName;
+(Class)safeCategoryBaseClass;
-(void)killSoundForBulletin:(id)arg1 ;
-(BOOL)_playSoundForBulletin:(id)arg1 playedInternally:(BOOL)arg2 ;
@end

