/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:52 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/FMCoreUI.framework/FMCoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIStoryboardSegue.h>

@interface FMPaneSegue : UIStoryboardSegue {

	BOOL _disableAnimation;

}

@property (assign,nonatomic) BOOL disableAnimation;              //@synthesize disableAnimation=_disableAnimation - In the implementation block
-(BOOL)disableAnimation;
-(void)perform;
-(void)performFromEdge:(unsigned long long)arg1 ;
-(void)setDisableAnimation:(BOOL)arg1 ;
@end

