/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:43 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/HealthKit.framework/HealthKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class _HKFactorization;

@interface _HKDimension : NSObject {

	_HKFactorization* _reduction;
	long long _reductionToken;

}
+(id)dimensionFromString:(id)arg1 ;
-(id)description;
-(id)_baseDimensions;
-(id)reduction;
@end

