/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:13:02 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/WelcomeKitUI.framework/WelcomeKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol WLSourceDevicesDelegate
@required
-(void)sourceDevices:(id)arg1 didChangeWithDevices:(id)arg2;
-(void)wifiAndDeviceDiscoveryDidGetInterrupted;

@end

