/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:14 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/vCard.framework/vCard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface CNVCardUnknownPropertyDescription : NSObject {

	NSString* _propertyName;
	NSString* _originalLine;

}

@property (copy) NSString * propertyName;              //@synthesize propertyName=_propertyName - In the implementation block
@property (copy) NSString * originalLine;              //@synthesize originalLine=_originalLine - In the implementation block
-(void)setPropertyName:(NSString *)arg1 ;
-(NSString *)propertyName;
-(BOOL)isEqual:(id)arg1 ;
-(id)description;
-(void)setOriginalLine:(NSString *)arg1 ;
-(NSString *)originalLine;
@end

