/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:11 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PhotoLibrary/PhotoLibrary-Structs.h>
#import <UIKit/UILabel.h>

@interface PLLabel : UILabel {

	double shadowBlurRadius;

}

@property (assign,nonatomic) double shadowBlurRadius; 
-(void)setShadowBlurRadius:(double)arg1 ;
-(double)shadowBlurRadius;
-(void)drawTextInRect:(CGRect)arg1 ;
@end

