/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:11 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol PLSlalomRegionEditorDelegate <NSObject>
@required
-(void)slalomRegionEditorDidBeginEditing:(id)arg1 withStartHandle:(BOOL)arg2;
-(void)slalomRegionEditorDidEndEditing:(id)arg1;
-(void)slalomRegionEditorStartValueChanged:(id)arg1;
-(void)slalomRegionEditorEndValueChanged:(id)arg1;
-(BOOL)slalomRegionEditorRequestForceZoom:(id)arg1;
-(void)slalomRegionEditorRequestForceUnzoom:(id)arg1;

@end

