/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:42 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _HKActiveWorkoutServer <NSObject>
@required
-(void)deactivateServer;
-(void)activateWorkoutWithCompletion:(/*^block*/id)arg1;
-(void)pauseWorkoutWithDate:(id)arg1 completion:(/*^block*/id)arg2;
-(void)resumeWorkoutWithDate:(id)arg1 completion:(/*^block*/id)arg2;
-(void)endWorkoutWithEndDate:(id)arg1 completion:(/*^block*/id)arg2;

@end

