/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:02 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/ReplayKit.framework/ReplayKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol RPDaemonProtocol <NSObject>
@required
-(oneway void)pauseRecording;
-(oneway void)startRecordingWindowLayerContextID:(unsigned)arg1 windowSize:(CGSize)arg2 microphoneEnabled:(BOOL)arg3 withHandler:(/*^block*/id)arg4;
-(oneway void)stopRecordingWithHandler:(/*^block*/id)arg1;
-(oneway void)discardRecordingWithHandler:(/*^block*/id)arg1;
-(oneway void)clientDidResignActiveWithBundleID:(id)arg1;
-(oneway void)clientDidBecomeActiveWithBundleID:(id)arg1;
-(oneway void)resumeRecordingWithWindowLayerContextID:(unsigned)arg1;

@end

