/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:31 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/CoreImage.framework/CoreImage
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreImage/CIReductionFilter.h>

@interface CIAreaMaximum : CIReductionFilter
-(id)_reduce2X2;
-(id)_reduce1X4;
-(id)_reduce4X1;
-(id)_reduceCrop;
-(id)outputImage;
@end

