/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:32 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/CoreImage.framework/CoreImage
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreImage/CoreImage-Structs.h>
#import <CoreImage/CICodeGenerator.h>

@class NSNumber;

@interface CICode128BarcodeGenerator : CICodeGenerator {

	NSNumber* inputQuietSpace;

}

@property (nonatomic,copy) NSNumber * inputQuietSpace; 
+(id)customAttributes;
-(NSNumber *)inputQuietSpace;
-(void)setInputQuietSpace:(NSNumber *)arg1 ;
-(CGImageRef)outputCGImage;
@end

