/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:40 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <iTunesStore/iTunesStore-Structs.h>
#import <iTunesStore/ISProtocolDataProvider.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface ISPropertyListProvider : ISProtocolDataProvider <NSCopying>
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)processDialogFromPropertyList:(id)arg1 returningError:(id*)arg2 ;
-(BOOL)processPropertyList:(id)arg1 returningError:(id*)arg2 ;
@end

