/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:46 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/SceneKit.framework/SceneKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <SceneKit/SceneKit-Structs.h>
@class SCNMetalRenderPipeline;

@interface SCNMTLShadableKey : NSObject {

	C3DMaterialRef _material;
	_C3DGeometry* _geometry;
	SCNMetalRenderPipeline* _pipeline;

}
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
@end

