/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:46 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/SceneKit.framework/SceneKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class SKScene, NSMutableDictionary;

@interface SCNSpriteKitEventHandler : NSObject {

	SKScene* _scene;
	NSMutableDictionary* _touchMap;

}

@property (nonatomic,retain) SKScene * scene;              //@synthesize scene=_scene - In the implementation block
-(void)dealloc;
-(id)init;
-(BOOL)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(BOOL)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(BOOL)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(BOOL)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(SKScene *)scene;
-(void)setScene:(SKScene *)arg1 ;
@end

