/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:25 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FrontBoardServices/FBSSettingsDiffInspector.h>

@interface FBSSceneClientSettingsDiffInspector : FBSSettingsDiffInspector
-(void)observeClassWithBlock:(/*^block*/id)arg1 ;
-(void)observePreferredLevelWithBlock:(/*^block*/id)arg1 ;
-(void)observePreferredInterfaceOrientationWithBlock:(/*^block*/id)arg1 ;
-(void)observePreferredSceneHostIdentifier:(/*^block*/id)arg1 ;
-(void)observeOcclusionsWithBlock:(/*^block*/id)arg1 ;
@end

