/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:40 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/FitnessUI.framework/FitnessUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class HKQuantity;

@interface _FIUIFakeStatistics : NSObject {

	HKQuantity* _sumQuantity;

}

@property (nonatomic,retain) HKQuantity * sumQuantity;              //@synthesize sumQuantity=_sumQuantity - In the implementation block
-(id)description;
-(HKQuantity *)sumQuantity;
-(void)setSumQuantity:(HKQuantity *)arg1 ;
@end

