/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:40 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/FitnessUI.framework/FitnessUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSAttributedString, UIView;

@interface FIUIPushyLabelCharacter : NSObject {

	NSAttributedString* _sourceText;
	UIView* _renderedView;

}

@property (retain) NSAttributedString * sourceText;              //@synthesize sourceText=_sourceText - In the implementation block
@property (retain) UIView * renderedView;                        //@synthesize renderedView=_renderedView - In the implementation block
-(NSAttributedString *)sourceText;
-(void)setSourceText:(NSAttributedString *)arg1 ;
-(UIView *)renderedView;
-(void)setRenderedView:(UIView *)arg1 ;
@end

