/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:44 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSMutableDictionary, NSObject;

@interface HMDSecureSessionNotifications : NSObject {

	NSMutableDictionary* _sessionNotificationPayloads;
	NSObject*<OS_dispatch_queue> _propertyQueue;

}

@property (nonatomic,retain) NSMutableDictionary * sessionNotificationPayloads;              //@synthesize sessionNotificationPayloads=_sessionNotificationPayloads - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> propertyQueue;                     //@synthesize propertyQueue=_propertyQueue - In the implementation block
-(id)init;
-(id)description;
-(NSObject*<OS_dispatch_queue>)propertyQueue;
-(void)setPropertyQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSMutableDictionary *)sessionNotificationPayloads;
-(id)_notificationPayloadsForDestination:(id)arg1 ;
-(void)addNotificationPayload:(id)arg1 identifier:(id)arg2 destination:(id)arg3 ;
-(void)removeNotificationPayloadWithIdentifier:(id)arg1 destination:(id)arg2 ;
-(id)notificationPayloadWithIdentifier:(id)arg1 destination:(id)arg2 ;
-(void)clearNotificationsForDestination:(id)arg1 ;
-(void)setSessionNotificationPayloads:(NSMutableDictionary *)arg1 ;
@end

