/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:08 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/MobileTimer.framework/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface WorldClockCellViewLayout : NSObject
+(id)cityNameConstraintsForViews:(id)arg1 ;
+(id)combinedLabelContainerConstraintsForViews:(id)arg1 ;
+(id)combinedDetailLabelConstraintsForViews:(id)arg1 ;
+(id)trailingLabelConstraintsForViews:(id)arg1 ;
+(id)analogClockConstraintsForViews:(id)arg1 ;
+(id)digitalClockConstraintsForViews:(id)arg1 ;
+(id)activeClockViewFromViews:(id)arg1 ;
+(id)constraintsForViews:(id)arg1 style:(long long)arg2 ;
@end

