/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:58 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/RemindersUI.framework/RemindersUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Social/SLComposeViewController.h>

@interface RMUIDetailEditorViewController : SLComposeViewController
-(id)init;
-(BOOL)setInitialURL:(id)arg1 ;
-(BOOL)setInitialTitle:(id)arg1 ;
-(BOOL)setInitialNotes:(id)arg1 ;
-(BOOL)attachCurrentUserActivity;
@end

