/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:13:05 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface HKCoordinateTransform : NSObject
-(id)valueForCoordinate:(double)arg1 ;
-(double)coordinateForValue:(id)arg1 ;
-(long long)compareValue:(id)arg1 toValue:(id)arg2 ;
@end

