/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:49 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/PrototypeTools.framework/PrototypeTools
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableSet;

@interface PTVolumeChangeNotifier : NSObject {

	NSMutableSet* ringerVolumeChangedHandlers;
	NSMutableSet* ringerSilentChangedHandlers;

}
+(id)sharedInstance;
-(id)init;
-(void)ringerVolumeChanged:(id)arg1 ;
-(void)addRingerSwitchChangedHandler:(/*^block*/id)arg1 ;
-(void)addVolumeChangedHandler:(/*^block*/id)arg1 ;
-(void)ringerSilentChanged;
@end

