/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:58 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MusicJSAccountNativeViewControllerDelegate <NSObject>
@required
-(void)jsAccountNativeViewController:(id)arg1 setAccountDocument:(id)arg2 options:(id)arg3;
-(void)jsDidCloseAccountNativeViewController:(id)arg1;

@end

