/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:59 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FuseUI/MusicLibraryViewConfiguration.h>

@class MusicLibraryViewConfiguration;

@interface MusicLibraryAdaptiveViewConfiguration : MusicLibraryViewConfiguration {

	MusicLibraryViewConfiguration* _compactWidthConfiguration;
	MusicLibraryViewConfiguration* _regularWidthConfiguration;

}

@property (nonatomic,readonly) MusicLibraryViewConfiguration * compactWidthConfiguration; 
@property (nonatomic,readonly) MusicLibraryViewConfiguration * regularWidthConfiguration; 
-(id)init;
-(MusicLibraryViewConfiguration *)compactWidthConfiguration;
-(MusicLibraryViewConfiguration *)regularWidthConfiguration;
-(void)enumerateContentViewConfigurationsUsingBlock:(/*^block*/id)arg1 ;
-(id)loadCompactWidthConfiguration;
-(id)loadRegularWidthConfiguration;
@end

