/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:20 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/SafariShared.framework/SafariShared
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <SafariShared/SafariShared-Structs.h>
@interface WBSParsecSearchMescalSession : NSObject {

	BOOL _complete;
	FPSAPContextOpaque_Ref _session;
	FairPlayHWInfo_ _hardwareInfo;
	unsigned long long _versionNumber;

}
-(void)dealloc;
-(id)init;
-(id)signatureStringForData:(id)arg1 ;
-(id)initWithVersionNumber:(unsigned long long)arg1 ;
-(id)exchangedDataForData:(id)arg1 ;
-(BOOL)_getHardwareInfo:(FairPlayHWInfo_*)arg1 ;
@end

