/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:20 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/SafariShared.framework/SafariShared
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol WBSURLCompletionDataSource <NSObject>
@required
-(id)fakeBookmarkMatchDataWithURLString:(id)arg1 title:(id)arg2;
-(void)enumerateMatchDataForTypedStringHint:(id)arg1 withBlock:(/*^block*/id)arg2;

@end

