/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:12 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/SlideshowKit.framework/Frameworks/OpusKit.framework/OpusKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OKPageSceneViewControllerExport <JSExport>
@optional
-(id)widgetNodeWithTemplateName:(id)arg1 name:(id)arg2 andSettings:(id)arg3 __JS_EXPORT_AS__widgetNodeWithTemplateName:(id)arg4;

@required
-(id)widgetNodeWithTemplateName:(id)arg1 name:(id)arg2 andSettings:(id)arg3;

@end

