/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:33 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol WPDeviceScannerDelegate <NSObject>
@optional
-(void)scanner:(id)arg1 foundDevice:(id)arg2 withData:(id)arg3;
-(void)scanner:(id)arg1 foundRequestedDevices:(id)arg2;
-(void)scanner:(id)arg1 didFailToRegisterDevices:(id)arg2 withError:(id)arg3;

@required
-(void)deviceScannerDidUpdateState:(id)arg1;

@end

