/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:58 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/PowerlogHelperdOperators.framework/PowerlogHelperdOperators
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate, NSString, NSMutableSet;

@interface PLBackgroundTransferEvent : NSObject {

	NSDate* _startDate;
	NSString* _bundleID;
	NSMutableSet* _taskUUIDs;

}

@property (retain) NSDate * startDate;                    //@synthesize startDate=_startDate - In the implementation block
@property (retain) NSString * bundleID;                   //@synthesize bundleID=_bundleID - In the implementation block
@property (retain) NSMutableSet * taskUUIDs;              //@synthesize taskUUIDs=_taskUUIDs - In the implementation block
-(id)description;
-(void)setBundleID:(NSString *)arg1 ;
-(NSString *)bundleID;
-(void)setStartDate:(NSDate *)arg1 ;
-(NSDate *)startDate;
-(NSMutableSet *)taskUUIDs;
-(void)setTaskUUIDs:(NSMutableSet *)arg1 ;
@end

