/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:15 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/VoiceMemos.framework/VoiceMemos
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@interface RCEntityRevision : NSManagedObject

@property (nonatomic,readonly) long long revisionType; 
@property (nonatomic,readonly) long long revisionID; 
@property (nonatomic,readonly) long long recordingID; 
-(long long)recordingID;
-(void)setRecordingID:(long long)arg1 ;
-(void)setRevisionID:(long long)arg1 ;
-(void)setRevisionType:(long long)arg1 ;
-(long long)revisionType;
-(long long)revisionID;
@end

