/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:15 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/VoiceMemos.framework/VoiceMemos
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <VoiceMemos/VoiceMemos-Structs.h>
@interface RCWaveformSnapshotGenerator : NSObject
+(id)snapshotForComposition:(id)arg1 size:(CGSize)arg2 ;
+(id)defaultUIConfiguration;
@end

