/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:06 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class MFMailMessage;

@interface _MFMailComposeAttachmentLoader : NSObject {

	MFMailMessage* _message;
	id _content;
	BOOL _isDraft;
	/*^block*/id _completionBlock;

}
-(void)dealloc;
-(id)initWithMessage:(id)arg1 content:(id)arg2 isDraft:(BOOL)arg3 completion:(/*^block*/id)arg4 ;
-(void)loadAttachments;
@end

