/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:06 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/MessageUI.framework/MessageUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MFComposeActivityContinuationOperationDelegate <NSObject>
@required
-(void)activityContinuationOperation:(id)arg1 didFailWithError:(id)arg2;
-(void)activityContinuationOperation:(id)arg1 didFinishSendingDataWithResult:(unsigned long long)arg2;
-(void)activityContinuationOperationReceivedBytes:(id)arg1;
-(void)activityContinuationOperation:(id)arg1 didFinishReceivingData:(id)arg2;

@end

