/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:13:02 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/VoiceTriggerUI.framework/VoiceTriggerUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface VTUIRegularExpressionMatcher : NSObject
+(long long)matchWithString:(id)arg1 TrailingStr:(id)arg2 LeadingStr:(id)arg3 Pattern:(id)arg4 ;
@end

