/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:08 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/DataDetectorsNaturalLanguage.framework/DataDetectorsNaturalLanguage
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <DataDetectorsNaturalLanguage/IPFeatureExtractor.h>

@interface IPSentenceFeatureExtractor : IPFeatureExtractor
+(unsigned long long)extractorVersion;
-(id)queueType;
-(id)featuresForTextUnit:(id)arg1 inMessageUnit:(id)arg2 context:(id)arg3 ;
-(unsigned long long)responseKitAnnotationTypeForFeatureDataType:(unsigned long long)arg1 ;
@end

