/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:54 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/RadioUI.framework/RadioUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, NSString, AVAssetCache;

@interface RUNetworkPlaybackController : NSObject {

	NSObject*<OS_dispatch_queue> _accessQueue;
	NSString* _highQualityAssetFlavor;
	double _minimumBitrateForHighQuality;
	AVAssetCache* _assetCache;

}

@property (nonatomic,readonly) AVAssetCache * assetCache;                           //@synthesize assetCache=_assetCache - In the implementation block
@property (nonatomic,copy,readonly) NSString * highQualityAssetFlavor; 
@property (nonatomic,readonly) double minimumBitrateForHighQuality; 
+(id)sharedController;
-(void)dealloc;
-(id)init;
-(id)_init;
-(double)minimumBitrateForHighQuality;
-(NSString *)highQualityAssetFlavor;
-(void)_updateForLoadedStoreBag:(id)arg1 ;
-(void)_radioStoreBagDidLoadNotification:(id)arg1 ;
-(AVAssetCache *)assetCache;
@end

