/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:12 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/MobileSpotlightIndex.framework/MobileSpotlightIndex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSpotlightIndex/MobileSpotlightIndex-Structs.h>
#import <MobileSpotlightIndex/_MDPlistBytes.h>

@interface _MDMutablePlistBytes : _MDPlistBytes {

	int _containerUID;
	int _currentUID;
	CFArrayRef _parentUIDStack;
	CFDictionaryRef _ptrUIDMap;
	unsigned long long* _fillPtr;
	unsigned long long* _limitPtr;
	unsigned long long* _rleTagPtr;

}
+(MDPlistBytesRef)createArrayPlistBytesUsingBlock:(/*^block*/id)arg1 ;
+(MDPlistBytesRef)createDictionaryPlistBytesUsingBlock:(/*^block*/id)arg1 ;
-(id)initWithCapacity:(unsigned long long)arg1 ;
-(id)initWithCapacity:(unsigned long long)arg1 useMalloc:(BOOL)arg2 ;
@end

