/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:06 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <GeoServices/GeoServices-Structs.h>
#import <GeoServices/GEOComposedRouteSection.h>
#import <libobjc.A.dylib/GEOComposedRouteTransitSection.h>

@class NSString;

@interface GEOComposedRouteTransitStationSection : GEOComposedRouteSection <GEOComposedRouteTransitSection> {

	SCD_Struct_GE16 _fromNodeLocation;
	SCD_Struct_GE16 _toNodeLocation;
	SCD_Struct_GE80 _fromNodeID;
	SCD_Struct_GE80 _toNodeID;
	int _toNodeSignificance;
	SCD_Struct_GE56 _originalBounds;

}

@property (nonatomic,readonly) SCD_Struct_GE80 fromNodeID;              //@synthesize fromNodeID=_fromNodeID - In the implementation block
@property (nonatomic,readonly) SCD_Struct_GE80 toNodeID;                //@synthesize toNodeID=_toNodeID - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) unsigned long long lineID; 
@property (nonatomic,readonly) BOOL isTransfer; 
@property (nonatomic,readonly) int toNodeSignificance;                  //@synthesize toNodeSignificance=_toNodeSignificance - In the implementation block
-(NSString *)description;
-(unsigned long long)lineID;
-(BOOL)isTransfer;
-(int)toNodeSignificance;
-(SCD_Struct_GE80)toNodeID;
-(id)initWithRoute:(id)arg1 startPoint:(unsigned)arg2 pointCount:(unsigned)arg3 step:(id)arg4 toNodeSignificance:(int)arg5 ;
-(SCD_Struct_GE80)fromNodeID;
@end

