/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:06 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <GeoServices/GeoServices-Structs.h>
@class GEOComposedRouteLeg, GEOComposedRouteStep;

@interface GEOComposedRouteSection : NSObject {

	unsigned _startPointIndex;
	unsigned _pointCount;
	SCD_Struct_GE97* _points;
	int _transportType;
	GEOComposedRouteLeg* _composedRouteLeg;
	GEOComposedRouteStep* _composedRouteStep;
	unsigned long long _composedRouteLegIndex;
	SCD_Struct_GE56 _bounds;
	SCD_Struct_GE56 _overlayBounds;
	unsigned long long _finalStepIndex;

}

@property (nonatomic,readonly) unsigned startPointIndex;                              //@synthesize startPointIndex=_startPointIndex - In the implementation block
@property (nonatomic,readonly) unsigned endPointIndex; 
@property (nonatomic,readonly) unsigned pointCount;                                   //@synthesize pointCount=_pointCount - In the implementation block
@property (nonatomic,readonly) SCD_Struct_GE97* points;                               //@synthesize points=_points - In the implementation block
@property (nonatomic,readonly) SCD_Struct_GE56 bounds;                                //@synthesize bounds=_bounds - In the implementation block
@property (nonatomic,readonly) GEOComposedRouteLeg * composedRouteLeg;                //@synthesize composedRouteLeg=_composedRouteLeg - In the implementation block
@property (nonatomic,readonly) GEOComposedRouteStep * composedRouteStep;              //@synthesize composedRouteStep=_composedRouteStep - In the implementation block
@property (nonatomic,readonly) unsigned long long composedRouteLegIndex;              //@synthesize composedRouteLegIndex=_composedRouteLegIndex - In the implementation block
@property (nonatomic,readonly) unsigned long long finalStepIndex;                     //@synthesize finalStepIndex=_finalStepIndex - In the implementation block
@property (nonatomic,readonly) int transportType;                                     //@synthesize transportType=_transportType - In the implementation block
-(SCD_Struct_GE56)bounds;
-(void)dealloc;
-(id)description;
-(int)transportType;
-(unsigned)pointCount;
-(SCD_Struct_GE97*)points;
-(BOOL)isTransfer;
-(GEOComposedRouteLeg *)composedRouteLeg;
-(unsigned long long)composedRouteLegIndex;
-(void)_initStepForRoute:(id)arg1 ;
-(GEOComposedRouteStep *)composedRouteStep;
-(id)initWithRoute:(id)arg1 startPoint:(unsigned)arg2 pointCount:(unsigned)arg3 bounds:(SCD_Struct_GE56)arg4 transportType:(int)arg5 finalStepIndex:(unsigned long long)arg6 ;
-(id)initWithRoute:(id)arg1 startPoint:(unsigned)arg2 pointCount:(unsigned)arg3 transportType:(int)arg4 finalStepIndex:(unsigned long long)arg5 fallbackStartCoordinate:(SCD_Struct_GE16)arg6 fallbackEndCoordinate:(SCD_Struct_GE16)arg7 ;
-(unsigned)endPointIndex;
-(unsigned)startPointIndex;
-(unsigned long long)finalStepIndex;
@end

