/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:00 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface GEOPowerAssertion : NSObject {

	NSString* _identifier;
	double _timeout;
	unsigned _assertion;

}
-(void)dealloc;
-(id)description;
-(id)initWithIdentifier:(id)arg1 timeout:(double)arg2 ;
@end

