/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:09 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface GEOPhoneNumberResolutionResultSet : NSObject {

	NSMutableDictionary* _results;

}
-(void)dealloc;
-(id)init;
-(id)description;
-(id)xpcDictionaryRepresentation;
-(id)initWithXPCDictionaryRepresentation:(id)arg1 ;
-(void)enumerateResolutionsUsingBlock:(/*^block*/id)arg1 ;
-(void)setError:(id)arg1 forPhoneNumber:(id)arg2 ;
-(void)setResult:(id)arg1 forPhoneNumber:(id)arg2 ;
@end

