/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:27 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/WatchConnectivity.framework/WatchConnectivity
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface WCActiveAppManager : NSObject
+(void)addActiveGlanceIdentifier:(id)arg1 ;
+(void)removeActiveGlanceIdentifier:(id)arg1 ;
+(void)addActiveNotificationIdentifier:(id)arg1 ;
+(void)removeActiveNotificationIdentifier:(id)arg1 ;
@end

