/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:30 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <AppPredictionInternal/AppPredictionInternal-Structs.h>
@class _DECAsset;

@interface _ATXBundleIdSet : NSObject {

	CFBurstTrieRef _trie;
	_DECAsset* _asset;

}
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
-(id)initWithAsset:(id)arg1 ;
-(BOOL)containsBundleId:(id)arg1 ;
-(CFBurstTrieRef)trie;
@end

