/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:54 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/Search.framework/Search
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSURL, NSString;


@protocol PRSBuyButton
@property (nonatomic,retain) NSURL * url; 
@property (nonatomic,retain) NSString * title; 
@property (nonatomic,retain) NSString * subtitle; 
@property (nonatomic,retain) NSString * adam_id; 
@property (nonatomic,retain) NSString * offer_type; 
@optional
-(void)setTitle:(id)arg1;
-(NSString *)title;
-(NSString *)subtitle;
-(void)setSubtitle:(id)arg1;
-(void)setAdam_id:(id)arg1;
-(void)setOffer_type:(id)arg1;
-(NSString *)adam_id;
-(NSString *)offer_type;

@required
-(NSURL *)url;
-(void)setUrl:(id)arg1;

@end

