/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:54 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/Search.framework/Search
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Search/SPProxyObject.h>
#import <libobjc.A.dylib/PRSApp.h>

@class NSString, NSURL;

@interface SPApp : SPProxyObject <PRSApp>

@property (nonatomic,retain) NSString * name; 
@property (nonatomic,retain) NSString * bundle_id; 
@property (nonatomic,retain) NSURL * install_url; 
@property (nonatomic,retain) NSString * label; 
@property (nonatomic,retain) NSURL * punchout_uri; 
@end

