/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:54 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/Search.framework/Search
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SPDomainManager : NSObject
+(id)defaultManager;
-(void)registerApplication:(id)arg1 withCategories:(id)arg2 ;
-(void)_removeAllDomainsForDisplayIdentifier:(id)arg1 ;
-(void)notifyIndexer;
-(void)applicationWasUninstalled:(id)arg1 ;
-(id)getBundleIdForDomainNumber:(id)arg1 ;
@end

