/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:50 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol BBLocalDataProviderFactoryStore
@required
-(void)removeDataProviderWithSectionID:(id)arg1;
-(void)addParentSectionInfo:(id)arg1 displayName:(id)arg2 icon:(id)arg3 universalSectionID:(id)arg4;
-(void)addParentSectionInfo:(id)arg1 displayName:(id)arg2 icon:(id)arg3;
-(void)addDataProvider:(id)arg1 performMigration:(BOOL)arg2;

@end

