/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:41 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _UIDocumentPickerExtensionViewController <NSObject>
@required
-(void)_setTintColor:(id)arg1;
-(void)_setPickableTypes:(id)arg1;
-(void)_setPickerMode:(unsigned long long)arg1;
-(void)_setUploadURLWrapper:(id)arg1;
-(void)_documentPickerDidDismiss;
-(void)_prepareWithExtensionInfo:(id)arg1 completionHandler:(/*^block*/id)arg2;

@end

