/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:50 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/_UIRemoteViewController.h>

@class _UIWebViewController;

@interface _UIRemoteWebViewController : _UIRemoteViewController {

	_UIWebViewController* _webViewController;

}

@property (assign,nonatomic) _UIWebViewController * webViewController;              //@synthesize webViewController=_webViewController - In the implementation block
+(id)serviceViewControllerInterface;
+(id)exportedInterface;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(BOOL)shouldAutorotateToInterfaceOrientation:(long long)arg1 ;
-(void)forwardInvocation:(id)arg1 ;
-(void)viewServiceDidTerminateWithError:(id)arg1 ;
-(_UIWebViewController *)webViewController;
-(void)setWebViewController:(_UIWebViewController *)arg1 ;
@end

