/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:40 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _UITouchable <NSObject>
@required
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
-(void)touchesEstimatedPropertiesUpdated:(id)arg1;

@end

