/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:44 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIKit/UIView.h>

@class UITableViewCell, UITableView;

@interface _UITableViewSeparatorView : UIView {

	UITableViewCell* _tableCell;
	UITableView* _table;

}
-(void)drawRect:(CGRect)arg1 ;
-(id)initWithFrame:(CGRect)arg1 withTable:(id)arg2 ;
-(id)initWithTableCell:(id)arg1 ;
@end

