/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:39 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <UIKit/UIKit-Structs.h>
@interface UIGradient : NSObject {

	SCD_Struct_UI25* _values;
	double _height;
	CGShadingRef _shader;

}
-(void)dealloc;
-(void)fillRect:(CGRect)arg1 inContext:(CGContextRef)arg2 ;
-(id)initVerticalWithValues:(SCD_Struct_UI25*)arg1 ;
-(void)fillRect:(CGRect)arg1 ;
@end

