/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:50 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIKit/UIKBContainerKeyView.h>

@class _UIFloatingContentView;

@interface UIKBFloatingKeyView : UIKBContainerKeyView {

	_UIFloatingContentView* _floatingContentView;

}

@property (nonatomic,readonly) _UIFloatingContentView * floatingContentView; 
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)arg1 keyplane:(id)arg2 key:(id)arg3 ;
-(_UIFloatingContentView *)floatingContentView;
-(void)prepareForDisplay;
@end

