/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:48 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIKit/UIKBCacheToken_Key.h>

@interface UIKBCacheToken_KeyMask : UIKBCacheToken_Key
+(id)tokenForKey:(id)arg1 style:(SCD_Struct_UI36)arg2 displayInsets:(UIEdgeInsets)arg3 ;
-(id)_stringWithAdditionalValues:(/*^block*/id)arg1 ;
@end

