/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:41 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <UIKit/UIButton.h>

@interface UIKeyboardCandidateLogButton : UIButton {

	SCD_Struct_UI36 _visualStyling;

}

@property (assign,nonatomic) SCD_Struct_UI36 visualStyling;              //@synthesize visualStyling=_visualStyling - In the implementation block
-(void)log;
-(void)setVisualStyling:(SCD_Struct_UI36)arg1 ;
-(id)initWithFrame:(CGRect)arg1 visualStyling:(SCD_Struct_UI36)arg2 ;
-(void)updateLabelColor;
-(SCD_Struct_UI36)visualStyling;
@end

