/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:38 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <QuartzCore/CALayer.h>

@class UIWindow;

@interface UIWindowLayer : CALayer {

	UIWindow* _window;

}
-(void)setFrame:(CGRect)arg1 ;
-(void)setBounds:(CGRect)arg1 ;
-(void)setTransform:(CATransform3D)arg1 ;
-(id)actionForKey:(id)arg1 ;
@end

