/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:02 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/WelcomeKit.framework/WelcomeKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WelcomeKit/WLDaemonController.h>

@protocol WLDeviceAuthenticatorProtocol, WLDeviceAuthenticationDelegate;
@class WLSourceDevice;

@interface WLDeviceAuthenticationController : WLDaemonController {

	id<WLDeviceAuthenticatorProtocol> _authenticator;
	WLSourceDevice* _device;
	id<WLDeviceAuthenticationDelegate> _delegate;

}

@property (nonatomic,readonly) WLSourceDevice * device;                                         //@synthesize device=_device - In the implementation block
@property (nonatomic,__weak,readonly) id<WLDeviceAuthenticationDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)authenticate;
-(id<WLDeviceAuthenticationDelegate>)delegate;
-(void)cancelAuthentication;
-(WLSourceDevice *)device;
-(id)initWithSourceDevice:(id)arg1 delegate:(id)arg2 ;
@end

