/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:21 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/MIME.framework/MIME
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface _MFEmailSetEmail : NSObject {

	unsigned long long _hash;
	NSString* _encodedAddress;
	NSString* _comment;

}

@property (nonatomic,readonly) unsigned long long hash; 
@property (nonatomic,retain) NSString * address; 
@property (nonatomic,readonly) NSString * commentedAddress; 
-(void)dealloc;
-(unsigned long long)hash;
-(id)description;
-(void)setAddress:(NSString *)arg1 ;
-(BOOL)isEqualToEmail:(id)arg1 ;
-(id)initWithAddress:(id)arg1 ;
-(NSString *)address;
-(NSString *)commentedAddress;
@end

