/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:50 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <OfficeImport/OfficeImport-Structs.h>
@interface ObjectCacheByCString : NSObject {

	CFDictionaryRef _dictionary;

}
-(void)dealloc;
-(id)init;
-(void)setObject:(id)arg1 forCStringKey:(char*)arg2 ;
-(id)getObjectForCStringKey:(char*)arg1 ;
@end

