/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:52 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ODIArrow : NSObject
+(void)mapWithState:(id)arg1 outward:(BOOL)arg2 ;
+(unsigned long long)nodeCountWithState:(id)arg1 ;
+(BOOL)mapIdentifier:(id)arg1 state:(id)arg2 ;
@end

