/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:51 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface TCXmlPrefixStreamWriterState : NSObject {

	NSString* _elementPrefix;
	NSString* _attributePrefix;

}

@property (nonatomic,copy) NSString * elementPrefix;                //@synthesize elementPrefix=_elementPrefix - In the implementation block
@property (nonatomic,copy) NSString * attributePrefix;              //@synthesize attributePrefix=_attributePrefix - In the implementation block
-(void)dealloc;
-(NSString *)elementPrefix;
-(void)setElementPrefix:(NSString *)arg1 ;
-(NSString *)attributePrefix;
-(void)setAttributePrefix:(NSString *)arg1 ;
@end

