/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:56 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <OfficeImport/OABReaderState.h>

@class WBReader, WXReadState;

@interface WBOfficeArtReaderState : OABReaderState {

	WBReader* mReader;
	int mCurrentTextType;
	WXReadState* mXmlDocumentState;

}

@property (assign,nonatomic) WBReader * reader; 
@property (assign,nonatomic) int currentTextType; 
-(void)dealloc;
-(id)initWithClient:(Class)arg1 ;
-(id)xmlDrawingState;
-(WBReader *)reader;
-(void)setReader:(WBReader *)arg1 ;
-(int)currentTextType;
-(void)setCurrentTextType:(int)arg1 ;
@end

