/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:49 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <OfficeImport/WMStyle.h>

@interface WMParagraphStyle : WMStyle {

	BOOL mIsInTextFrame;

}
+(BOOL)isShadingNull:(id)arg1 ;
-(void)mapBorders:(id)arg1 ;
-(void)addParagraphProperties:(id)arg1 fromListLevelProperties:(BOOL)arg2 ;
-(id)initWithWDStyle:(id)arg1 isInTextFrame:(BOOL)arg2 ;
-(void)addParagraphStyleCharacterProperties:(id)arg1 ;
-(BOOL)isRTLWithOverridesFromProperties:(id)arg1 ;
-(id)leadingMarginPropertyNameWithOverridesFromProperties:(id)arg1 ;
-(id)initWithWDParagraphProperties:(id)arg1 isInTextFrame:(BOOL)arg2 ;
@end

