/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:11 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/PreferencesUI.framework/PreferencesUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class ALCity;

@interface TimeZoneTableCell : UITableViewCell {

	ALCity* _city;

}

@property (nonatomic,retain) ALCity * city;              //@synthesize city=_city - In the implementation block
-(id)_contentString;
-(void)setCity:(ALCity *)arg1 ;
-(ALCity *)city;
@end

