/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:42 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/CoreMediaStream.framework/CoreMediaStream
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface MSProtocolUtilities : NSObject
+(id)deviceInfoDictForPersonID:(id)arg1 ;
+(id)Win32SHA1OfUDID:(id)arg1 ;
+(id)retryAfterDateBasedOnRetryAfterHeaderString:(id)arg1 ;
@end

