/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:13:02 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/WelcomeKitCore.framework/WelcomeKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WelcomeKitCore/WelcomeKitCore-Structs.h>
#import <WelcomeKitCore/WLMigrationWebService.h>

@interface WLFileMigrationWebService : WLMigrationWebService
-(id)urlForRecordSummariesWithAccount:(id)arg1 ;
-(id)urlForRecordWithSummary:(id)arg1 account:(id)arg2 segmentByteRange:(NSRange*)arg3 ;
-(void)fetchAccountsAndSummariesWithStatistics:(id)arg1 completion:(/*^block*/id)arg2 ;
@end

