/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:13:02 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/WelcomeKitCore.framework/WelcomeKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSDictionary;

@interface WLMessageSMILPart : NSObject {

	NSString* _elementName;
	NSDictionary* _attributes;

}

@property (nonatomic,readonly) NSString * elementName;                 //@synthesize elementName=_elementName - In the implementation block
@property (nonatomic,readonly) NSDictionary * attributes;              //@synthesize attributes=_attributes - In the implementation block
-(NSDictionary *)attributes;
-(NSString *)elementName;
-(id)fileName;
-(id)initWithElementName:(id)arg1 attributes:(id)arg2 ;
@end

