/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:39 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/DataAccess.framework/Frameworks/DACardDAV.framework/DADaemonCardDAV.bundle/DADaemonCardDAV
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface CardDAVSyncInfo : NSObject {

	NSMutableDictionary* _uuidToPersonCache;
	BOOL _startedWithNoContacts;

}

@property (nonatomic,retain) NSMutableDictionary * uuidToPersonCache;              //@synthesize uuidToPersonCache=_uuidToPersonCache - In the implementation block
@property (assign,nonatomic) BOOL startedWithNoContacts;                           //@synthesize startedWithNoContacts=_startedWithNoContacts - In the implementation block
-(NSMutableDictionary *)uuidToPersonCache;
-(void)setUuidToPersonCache:(NSMutableDictionary *)arg1 ;
-(BOOL)startedWithNoContacts;
-(void)setStartedWithNoContacts:(BOOL)arg1 ;
@end

