/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:05 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/UIAccessibility.framework/UIAccessibility
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIAccessibility/__UITouchesEventAccessibility_super.h>

@interface UITouchesEventAccessibility : __UITouchesEventAccessibility_super
+(id)safeCategoryTargetClassName;
+(Class)safeCategoryBaseClass;
-(void)_setAccessibilityHitTestsAnyElement:(BOOL)arg1 ;
-(void)_setAccessibilityHitTestStartsAtElement:(id)arg1 ;
-(BOOL)_accessibilityHitTestsAnyElement;
-(id)_accessibilityHitTestStartsAtElement;
@end

