/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:33 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/CloudDocsDaemon.framework/CloudDocsDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/BRContainerHelper.h>

@class NSString;

@interface BRCDaemonContainerHelper : NSObject <BRContainerHelper>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)disabledBundleURLs;
+(BOOL)cloudSyncTCCDisabledForContainerMeta:(id)arg1 disabledBundleURLs:(id)arg2 ;
+(BOOL)cloudSyncTCCDisabledForContainerMeta:(id)arg1 ;
-(BOOL)canFetchAllContainersByID;
-(id)fetchAllContainersByID;
-(id)fetchContainerForURL:(id)arg1 ;
@end

