/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:46 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/PowerlogCore.framework/PowerlogCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PLValueUtilties : NSObject
+(long long)compare:(id)arg1 with:(id)arg2 ;
+(BOOL)isNil:(id)arg1 ;
+(BOOL)isFormater:(short)arg1 validForObject:(id)arg2 ;
+(id)formattedStringForDate:(id)arg1 ;
+(void)resetTimestampFormaterTimezone;
@end

