/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:46 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/PowerlogCore.framework/PowerlogCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct __IOHIDEventSystemClient* IOHIDEventSystemClientRef;

typedef struct __IOHIDEvent* IOHIDEventRef;

typedef struct IONotificationPort* IONotificationPortRef;

typedef struct __CFRunLoopSource* CFRunLoopSourceRef;

typedef struct __CFFileDescriptor* CFFileDescriptorRef;

typedef struct PLTimeIntervalRange {
	double location;
	double length;
} PLTimeIntervalRange;

typedef struct sqlite3* sqlite3Ref;

typedef struct __CFData* CFDataRef;

typedef struct _NSZone* NSZoneRef;

typedef struct sqlite3_stmt* sqlite3_stmtRef;

