/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:12 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray, NSString;

@interface SUCompletionsResponse : NSObject {

	NSArray* _completionItems;
	NSString* _title;

}

@property (nonatomic,readonly) NSArray * completionItems;              //@synthesize completionItems=_completionItems - In the implementation block
@property (nonatomic,readonly) NSString * title;                       //@synthesize title=_title - In the implementation block
-(void)dealloc;
-(id)init;
-(NSString *)title;
-(NSArray *)completionItems;
-(id)initWithPropertyList:(id)arg1 ;
@end

