/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:45 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/CameraKit.framework/CameraKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CameraKit/CameraKit-Structs.h>
#import <UIKit/UIView.h>

@class UILabel;

@interface CMKSlalomIndicatorView : UIView {

	long long _framesPerSecond;
	UILabel* __framerateLabel;

}

@property (assign,nonatomic) long long framesPerSecond;                //@synthesize framesPerSecond=_framesPerSecond - In the implementation block
@property (nonatomic,readonly) UILabel * _framerateLabel;              //@synthesize _framerateLabel=__framerateLabel - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)layoutSubviews;
-(UIEdgeInsets)alignmentRectInsets;
-(CGSize)intrinsicContentSize;
-(void)_commonCMKSlalomIndicatorViewInitialization;
-(void)_updateFramerateLabel;
-(void)setFramesPerSecond:(long long)arg1 ;
-(long long)framesPerSecond;
-(UILabel *)_framerateLabel;
@end

