/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:02 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/GameController.framework/GameController
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct __IOHIDManager* IOHIDManagerRef;

typedef struct IONotificationPort* IONotificationPortRef;

typedef struct __CFRunLoop* CFRunLoopRef;

typedef struct __CFRunLoopSource* CFRunLoopSourceRef;

typedef struct {
	float field1[4];
} SCD_Struct_GC4;

typedef struct __IOHIDValue* IOHIDValueRef;

typedef struct __IOHIDElement* IOHIDElementRef;

typedef struct BTSessionImpl* BTSessionImplRef;

typedef struct BTPairingAgentImpl* BTPairingAgentImplRef;

typedef struct BTDiscoveryAgentImpl* BTDiscoveryAgentImplRef;

typedef struct __IOHIDDevice* IOHIDDeviceRef;

typedef struct _NSZone* NSZoneRef;

typedef struct {
	double x;
	double y;
	double z;
} SCD_Struct_GC12;

typedef struct GCQuaternion {
	double x;
	double y;
	double z;
	double w;
} GCQuaternion;

