/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:24 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct __CFData* CFDataRef;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct __CFArray* CFArrayRef;

typedef struct _NSZone* NSZoneRef;

typedef struct __asl_object_s* asl_object_sRef;

