/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:01 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/Accessibility.framework/Frameworks/AccessibilityUIUtilities.framework/AccessibilityUIUtilities
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface AXUIReachabilityHelper : NSObject
+(id)sharedHelper;
-(id)_animationFactoryWithPayload:(id)arg1 ;
-(double)reachabilityOffsetForPayload:(id)arg1 ;
-(void)animateForReachability:(/*^block*/id)arg1 payload:(id)arg2 completion:(/*^block*/id)arg3 ;
@end

