/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:46 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/MetalTools.framework/MetalTools
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MetalTools/MetalTools-Structs.h>
#import <MetalTools/MTLToolsCommandBuffer.h>

@class _MTLCommandEncoder;

@interface MTLDebugCommandBuffer : MTLToolsCommandBuffer {

	_MTLCommandEncoder* _currentEncoder;

}
-(id)parallelRenderCommandEncoderWithDescriptor:(id)arg1 ;
-(id)sampledRenderCommandEncoderWithDescriptor:(id)arg1 programInfoBuffer:(SCD_Struct_MT1*)arg2 capacity:(unsigned long long)arg3 ;
-(void)waitUntilScheduled;
-(id)fragmentRenderCommandEncoderWithDescriptor:(id)arg1 ;
-(id)computeCommandEncoder;
-(id)blitCommandEncoder;
-(void)waitUntilCompleted;
-(id)renderCommandEncoderWithDescriptor:(id)arg1 ;
-(id)sampledComputeCommandEncoderWithProgramInfoBuffer:(SCD_Struct_MT1*)arg1 capacity:(unsigned long long)arg2 ;
-(id)initWithCommandBuffer:(id)arg1 commandQueue:(id)arg2 ;
@end

