/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:35 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/SSCacheObjectFactory.h>

@class NSString;

@interface SSPlistCacheObjectFactory : NSObject <SSCacheObjectFactory>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)supportsTypeIdentifier:(id)arg1 ;
-(id)cachedObjectWithDataRepresentation:(id)arg1 typeIdentifier:(id)arg2 ;
@end

