/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:33 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <StoreServices/StoreServices-Structs.h>
#import <StoreServices/SSPurchase.h>
#import <libobjc.A.dylib/SSXPCCoding.h>
#import <libobjc.A.dylib/NSCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSArray, NSNumber, NSString;

@interface SSTonePurchase : SSPurchase <SSXPCCoding, NSCoding, NSCopying> {

	NSArray* _allowedToneStyles;
	NSNumber* _assigneeIdentifier;
	NSString* _assigneeToneStyle;
	BOOL _shouldMakeDefaultRingtone;
	BOOL _shouldMakeDefaultTextTone;

}

@property (copy) NSArray * allowedToneStyles; 
@property (retain) NSNumber * assigneeIdentifier; 
@property (copy) NSString * assigneeToneStyle; 
@property (assign) BOOL shouldMakeDefaultRingtone; 
@property (assign) BOOL shouldMakeDefaultTextTone; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_setValuesUsingDatabaseEncoding:(id)arg1 ;
-(void)_addEntriesToDatabaseEncoding:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)copyXPCEncoding;
-(id)initWithXPCEncoding:(id)arg1 ;
-(void)setAllowedToneStyles:(NSArray *)arg1 ;
-(id)initWithItem:(id)arg1 offer:(id)arg2 ;
-(NSArray *)allowedToneStyles;
-(NSNumber *)assigneeIdentifier;
-(void)setAssigneeIdentifier:(NSNumber *)arg1 ;
-(NSString *)assigneeToneStyle;
-(void)setAssigneeToneStyle:(NSString *)arg1 ;
-(BOOL)shouldMakeDefaultRingtone;
-(void)setShouldMakeDefaultRingtone:(BOOL)arg1 ;
-(BOOL)shouldMakeDefaultTextTone;
-(void)setShouldMakeDefaultTextTone:(BOOL)arg1 ;
@end

