/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:04 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/QuickLookThumbnailing.framework/QuickLookThumbnailing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSOperationQueue, NSMutableDictionary;

@interface QLThumbnailGenerationQueue : NSObject {

	NSOperationQueue* _queue;
	NSMutableDictionary* _queuedURLs;

}
+(id)sharedInstance;
-(void)dealloc;
-(id)init;
-(void)noteThumbnailGenerationQueuedExternallyForDocumentAtURL:(id)arg1 ;
-(void)enqueueThumbnailGenerationIfNeededForDocumentAtURL:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
@end

