/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:48 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/CallHistory.framework/CallHistory
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CHLoggerProtocol
@required
-(BOOL)shouldLogForLevel:(unsigned)arg1;
-(void)logWithLevel:(unsigned)arg1 withFormat:(id)arg2;

@end

