/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:34 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/MediaPlayerUI.framework/MediaPlayerUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class MPArtworkCatalog;

@interface MPUExtrasSlideshowArtworkCatalogHelper : NSObject {

	MPArtworkCatalog* _artworkCatalog;

}

@property (nonatomic,retain) MPArtworkCatalog * artworkCatalog;              //@synthesize artworkCatalog=_artworkCatalog - In the implementation block
-(void)setArtworkCatalog:(MPArtworkCatalog *)arg1 ;
-(MPArtworkCatalog *)artworkCatalog;
@end

