/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:36 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ABTableViewHelper : NSObject
+(void)syncTableView:(id)arg1 withIndexPath:(id)arg2 animated:(BOOL)arg3 styleProvider:(id)arg4 ;
+(void)prepareCell:(id)arg1 asSelectedCell:(BOOL)arg2 styleProvider:(id)arg3 ;
+(id)newOverlayLabel;
@end

