/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:34 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/Notes.framework/Notes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ICNoteSnippetUtilities : NSObject
+(id)stringByRemovingTitle:(id)arg1 fromString:(id)arg2 ;
+(id)snippetForContent:(id)arg1 ;
+(id)snippetAndTitleTrimCharacterSet;
@end

