/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:03 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/AirPortAssistant.framework/AirPortAssistant
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/AUUIAlertDelegate.h>

@class AUUIAlert, NSString;

@interface AUUIAlertDelegateClass : NSObject <AUUIAlertDelegate> {

	AUUIAlert* uiAlert;

}

@property (nonatomic,retain) AUUIAlert * uiAlert; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(AUUIAlert *)uiAlert;
-(void)setUiAlert:(AUUIAlert *)arg1 ;
-(BOOL)auUIAlertOKAction:(id)arg1 ;
-(BOOL)auUIAlertCancelAction:(id)arg1 ;
@end

