/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:33 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/WatchKit.framework/WatchKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WatchKit/WKInterfaceObject.h>

@interface WKInterfaceMovie : WKInterfaceObject
-(void)setPosterImage:(id)arg1 ;
-(void)setVideoGravity:(long long)arg1 ;
-(void)setMovieURL:(id)arg1 ;
-(void)setLoops:(BOOL)arg1 ;
@end

