/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:18 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SAObjects/SASettingSnippet.h>

@class NSNumber;

@interface SASettingBoolSnippet : SASettingSnippet

@property (assign,nonatomic) BOOL toggle; 
@property (nonatomic,copy) NSNumber * value; 
+(id)boolSnippet;
+(id)boolSnippetWithDictionary:(id)arg1 context:(id)arg2 ;
-(NSNumber *)value;
-(void)setValue:(NSNumber *)arg1 ;
-(id)groupIdentifier;
-(void)setToggle:(BOOL)arg1 ;
-(BOOL)toggle;
-(id)encodedClassName;
@end

