/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:08 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/Social.framework/Social
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSArray;

@interface SLFacebookPostPrivacyCategory : NSObject {

	NSString* _name;
	NSArray* _audiencePrivacySettings;

}

@property (retain) NSString * name;                                //@synthesize name=_name - In the implementation block
@property (retain) NSArray * audiencePrivacySettings;              //@synthesize audiencePrivacySettings=_audiencePrivacySettings - In the implementation block
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(NSArray *)audiencePrivacySettings;
-(void)setAudiencePrivacySettings:(NSArray *)arg1 ;
@end

