/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:09 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/Social.framework/Social
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSXPCInterface, NSXPCConnection, NSMutableArray, NSLock, NSObject;

@interface SLRemoteSessionProxy : NSObject {

	NSString* _serviceName;
	NSXPCInterface* _remoteInterface;
	id _remoteProxy;
	NSXPCConnection* _connection;
	NSMutableArray* _guaranteedRemoteCalls;
	NSLock* _guaranteedRemoteCallsLock;
	NSObject* _exportedObject;
	NSXPCInterface* _exportedInterface;
	/*^block*/id _connectionResetBlock;

}

@property (__weak) NSObject * exportedObject;                       //@synthesize exportedObject=_exportedObject - In the implementation block
@property (retain) NSXPCInterface * exportedInterface;              //@synthesize exportedInterface=_exportedInterface - In the implementation block
@property (copy) id connectionResetBlock;                           //@synthesize connectionResetBlock=_connectionResetBlock - In the implementation block
-(NSObject *)exportedObject;
-(void)dealloc;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(void)forwardInvocation:(id)arg1 ;
-(NSXPCInterface *)exportedInterface;
-(void)disconnect;
-(void)setExportedInterface:(NSXPCInterface *)arg1 ;
-(void)setExportedObject:(NSObject *)arg1 ;
-(void)_setupConnection;
-(id)initForRemoteServiceName:(id)arg1 remoteInterface:(id)arg2 ;
-(void)setConnectionResetBlock:(id)arg1 ;
-(void)dropGuaraneteedRemoteCall:(id)arg1 ;
-(void)registerGuaranteedRemoteCall:(id)arg1 ;
-(id)connectionResetBlock;
-(void)_remoteSessionConnectionWasInterrupted;
@end

