/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:40 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface GKCachePair : NSObject {

	id _value;
	id _key;

}

@property (nonatomic,retain) id value;              //@synthesize value=_value - In the implementation block
@property (nonatomic,retain) id key;                //@synthesize key=_key - In the implementation block
-(void)dealloc;
-(id)key;
-(id)value;
-(void)setValue:(id)arg1 ;
-(void)setKey:(id)arg1 ;
@end

