/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:38 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/CoreCDPInternal.framework/CoreCDPInternal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CDPDRemoteDeviceSecretValidatorDelegate <NSObject>
@required
-(void)remoteSecretValidator:(id)arg1 recoverSecureBackupWithSecret:(id)arg2 device:(id)arg3 completion:(/*^block*/id)arg4;
-(BOOL)remoteSecretValidator:(id)arg1 applyToJoinCircleWithJoinHandler:(/*^block*/id)arg2;
-(void)cancelRemoteSecretValidatorApplicationToJoinCircle:(id)arg1;

@end

