/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:37 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/CoreCDPInternal.framework/CoreCDPInternal
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class CDPContext, NSObject;

@interface CDPDCircleStateObserver : NSObject {

	CDPContext* _context;
	int _circleChangeToken;
	BOOL _isObserving;
	NSObject*<OS_dispatch_queue> _eventQueue;

}
-(void)dealloc;
-(id)initWithContext:(id)arg1 ;
-(const char*)_notificationName;
-(void)observeCircleStateWithChangeHandler:(/*^block*/id)arg1 ;
-(void)observeChangeToState:(int)arg1 handler:(/*^block*/id)arg2 ;
-(void)stopObservingCircleStatusChange;
@end

