/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:54 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TelephonyUI/TPBottomBar.h>

@class TPButton;

@interface TPBottomSingleButtonBar : TPBottomBar {

	id _delegate;
	TPButton* _button;

}
+(id)_backgroundImage;
-(id)button;
-(double)buttonWidth;
-(void)setButton:(id)arg1 andStyle:(BOOL)arg2 ;
@end

