/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:57 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/AVFoundation.framework/libAVFAudio.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAVFAudio.dylib/AVAudioUnitTimeEffect.h>

@interface AVAudioUnitVarispeed : AVAudioUnitTimeEffect

@property (assign,nonatomic) float rate; 
-(id)init;
-(void)setRate:(float)arg1 ;
-(float)rate;
@end

