/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:57 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/AVFoundation.framework/libAVFAudio.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libAVFAudio.dylib/libAVFAudio.dylib-Structs.h>
@interface AVAudioUnitEQFilterParameters : NSObject {

	void* _impl;

}

@property (assign,nonatomic) long long filterType; 
@property (assign,nonatomic) float frequency; 
@property (assign,nonatomic) float bandwidth; 
@property (assign,nonatomic) float gain; 
@property (assign,nonatomic) BOOL bypass; 
-(void)dealloc;
-(id)init;
-(float)frequency;
-(void)setFrequency:(float)arg1 ;
-(long long)filterType;
-(void)setFilterType:(long long)arg1 ;
-(float)gain;
-(void)setGain:(float)arg1 ;
-(id)initWithImpl:(AVAudioUnitEQFilterParametersImpl*)arg1 ;
-(BOOL)bypass;
-(void)setBypass:(BOOL)arg1 ;
-(void)setBandwidth:(float)arg1 ;
-(float)bandwidth;
@end

