/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:09:57 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AVFoundation/AVFoundation-Structs.h>
#import <Foundation/NSValue.h>

@interface CMTimeMappingAsValue : NSValue {

	SCD_Struct_CM7 _timeMapping;

}
+(id)valueWithCMTimeMapping:(SCD_Struct_CM7)arg1 ;
-(id)description;
-(void)getValue:(void*)arg1 ;
-(const char*)objCType;
-(SCD_Struct_CM7)CMTimeMappingValue;
@end

