/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:00 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/Frameworks/Photos.framework/Photos
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol PHDeleteChangeRequest <PHChangeRequest>
@required
-(BOOL)validateForDeleteManagedObject:(id)arg1 error:(id*)arg2;
-(void)deleteManagedObject:(id)arg1 photoLibrary:(id)arg2;

@end

