/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:15 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/WebContentAnalysis.framework/WebContentAnalysis
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface WFJavascriptStripper : NSObject
+(id)getStringsFromLine:(id)arg1 withTokenCharacter:(id)arg2 ;
+(id)getJavascriptLines:(id)arg1 ;
+(id)javascriptStripLine:(id)arg1 ;
+(id)stripJavascript:(id)arg1 ;
@end

