/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:12:36 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface CKPackageManifest : NSObject
+(BOOL)readContentsOfFile:(id)arg1 intoPackage:(id)arg2 error:(id*)arg3 ;
+(BOOL)writePackage:(id)arg1 toFile:(id)arg2 error:(id*)arg3 ;
+(id)packageWithContentsOfFile:(id)arg1 error:(id*)arg2 ;
@end

