/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:11:31 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/MPUFoundation.framework/MPUFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MPUFoundation/MPUModelObject.h>

@class NSString;

@interface MPUModelGenre : MPUModelObject {

	NSString* _name;

}

@property (nonatomic,copy) NSString * name;              //@synthesize name=_name - In the implementation block
+(id)__name__KEY;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(id)descriptionWithType:(unsigned long long)arg1 ;
@end

