/*
* This header is generated by classdump-dyld 1.0
* on Sunday, July 31, 2016 at 10:10:52 PM Australian Western Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AccessibilityUtilities/AXLoggingSubsystem.h>

@interface AXSubsystemVOTHandwriting : AXLoggingSubsystem
+(id)identifier;
+(BOOL)shouldProcessMessageForLogs;
+(BOOL)shouldLogToFile;
+(BOOL)shouldIncludeFileLineAndFunctionInLogs;
+(int)defaultLogLevel;
+(double)threshold;
@end

